// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMq5e2fP6GxzTAU1L71H3TncNnaCxJ7w',
    appId: '1:788318756405:web:2f054cd1a1c6c2644b9b7c',
    messagingSenderId: '788318756405',
    projectId: 'cars-be078',
    authDomain: 'cars-be078.firebaseapp.com',
    storageBucket: 'cars-be078.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0zdB8WutWK5ND1CvPdmh1O9Zktxpm_BY',
    appId: '1:788318756405:android:4103d8be4ba2bd984b9b7c',
    messagingSenderId: '788318756405',
    projectId: 'cars-be078',
    storageBucket: 'cars-be078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCE_m7IbLmwzBsgE9TIAI4rvHDPrLHhKo',
    appId: '1:788318756405:ios:191f7cc067257f874b9b7c',
    messagingSenderId: '788318756405',
    projectId: 'cars-be078',
    storageBucket: 'cars-be078.appspot.com',
    iosClientId: '788318756405-h744afbuts684vh3sgps2fs49lknuo52.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCE_m7IbLmwzBsgE9TIAI4rvHDPrLHhKo',
    appId: '1:788318756405:ios:191f7cc067257f874b9b7c',
    messagingSenderId: '788318756405',
    projectId: 'cars-be078',
    storageBucket: 'cars-be078.appspot.com',
    iosClientId: '788318756405-h744afbuts684vh3sgps2fs49lknuo52.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );
}
